import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Animation from "@/components/Animation";
import { Toaster } from "react-hot-toast";
import { NavbarDemo } from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} scroll-container antialiased dark`}
      >
        <Toaster position="top-right" reverseOrder={false} />
        <NavbarDemo />
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
